variable "tagname" {}
variable "dominio" {}
variable "projeto" {}
variable "image_url" {}
variable "taskdefinition_name" {}
variable "container_name" {}
variable "subnets" {}
variable "security_group_id" {}
variable "website_zone_id" {}
variable "vpc_id" {}
variable "website_certificado_arn" {}