variable "tagname" {}
variable "dominio" {}
variable "projeto" {}
variable "subnets" {}
variable "security_group_id" {}
variable "website_zone_id" {}
variable "vpc_id" {}
variable "website_certificado_arn" {}
variable "sqs_name" {}
variable "docker_username" {}
variable "docker_userpass" {}
